---
# defaults file for logstash
logstashclient: True
logstash_private_key: |
   -----BEGIN PRIVATE KEY-----
   MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCkKT+XSPik7jOP
   V+5YpZVgFo9uP7oRwQ5Wf5hLwdEb7202q0JIGRLyVxkILr/OJbG5RMy41z1kPUIY
   l9WPCcDcpqtOEoGGoP4SkIw8jk1v5Pd5+bkIHLulmZwLeedn0OZLUwXWiUPSAyGH
   NqctPxQwOKkH1TMdGTJXMIQoO2KIGXr3Y+LHSAZ8mE3X6yDPnJ5vZW2oq3PPI7O5
   ZemRwFm24zWaW2kM1yblFjC1osIhEl1bA3gEVvbKLGEcKmKtYIuhWG8avC3PSH7W
   Gpuc0acsdFDjfb4Cju6cZlrEbfqWDfmHPHdS7DroIr+RSMjWqXO5jgkOVNLwCKwa
   RFE+b6+VAgMBAAECggEAeq480MF+2DsPmzNaczMjo9CYVgsX8ga1wVzPouXwcREI
   LE/mU90xNJx0n5HYU6YF4HATEpwATDYffCOUPLZMRFnmMY1Q8RzFY3hU5ThvlIyn
   iadfaTmX3lUisczja8lJIcek2ERyw7MFTnhAjWbTnonpgGoLLdbTsScXzL08kHpP
   uPhGaaFYScdNJjCJ7qYsXj2a9f6PrTE3ErxJgbjlRE2voZyT2KYVb0/XwNG0+eFC
   f36ARWyMRJxGZtCsB3WgBz2MM9M3kcatbBLGCpucVbqWeZKcnKXc8ieirJIU7rBD
   rVrmbFqbCM63cvO+Rw5xMg5EhJSaQZuX1jqmqnBgoQKBgQDUi7rYzpilJw8gSJ+j
   ddJX2bHPVI9675zaD0w6BSTxrs1jE5sGQr42dp3kXrqHi/MxsHpA5MGSAKpe8ezL
   av6KTcmlvfodjYVjBqSqggI5xrDG4716SAnborUrtBgzTVg6rb1XNYIu1cZVvms3
   SO4g5gFGamq5Il5y1KwW2juumQKBgQDFuSZWVRPqaPoclyxriU1wx5vPBlxpYREQ
   nuxZ594Myf1JlYmVkBLQEcdxuW7AIhCnQ4SnRz3IAmZ5DSWkThkk7tuRa/Cs4dy0
   NV06bSGXB0GAiZRw31H7nbXnmECnW+r9jylE0ohskxoWXJF9PNCcj2y3VdAWT4jL
   iyb5+V6SXQKBgCpfJMOeBA5AiCJud+y1S1aaHnlvqR7f78wE6rRSXDgWGfnbabdI
   zPS8luN1AwiMnNHWFbkkIXbCzTQaVJOE4/OcaEuzYM5NbT79jwwy2NC9zHYJ5rce
   72AqwqVQxNZNX/5qrmlZUHeXxG9Jg8REtLw4Ph7UjiwULvIDdb8kiGtZAoGAK5bV
   zNKUwWjDOupY8JwkZmibANj2JoUvrepbULa9TTR6km5VFpPckeJZhcjLka/w2+8W
   n4olJKLi1G0Bj2doQ6wk27pgJLzmWxQoqWjFrvX6isvJ3dhdyorKP3RhTIQHGj8l
   afa//K+xYJyntmRh2SIFZaWValW+YqEaxqEjKEECgYAlKs0ZNLtrtNfxhvBLmvFk
   mfn4W9xWv+OODtt1FkY8NYtAHH+01GTmRxYUCVr17/evFVKmBGh2Pr4XCALp6mRe
   NnCjvPN+lAOPFbxKKcNEkZS2Kq/9A6QCrX95cTmRYernqKtFyjeX7FCNX0Tm2ek1
   Dbdpky7Uq7kiRSCSPuD/xA==
   -----END PRIVATE KEY-----
logstash_cert: | 
   -----BEGIN CERTIFICATE-----
   MIIDXTCCAkWgAwIBAgIJAIJtBQUKwuQeMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
   BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
   aWRnaXRzIFB0eSBMdGQwHhcNMTUwMzA1MTUxNjE5WhcNMjUwMzAyMTUxNjE5WjBF
   MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
   ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
   CgKCAQEApCk/l0j4pO4zj1fuWKWVYBaPbj+6EcEOVn+YS8HRG+9tNqtCSBkS8lcZ
   CC6/ziWxuUTMuNc9ZD1CGJfVjwnA3KarThKBhqD+EpCMPI5Nb+T3efm5CBy7pZmc
   C3nnZ9DmS1MF1olD0gMhhzanLT8UMDipB9UzHRkyVzCEKDtiiBl692Pix0gGfJhN
   1+sgz5yeb2VtqKtzzyOzuWXpkcBZtuM1mltpDNcm5RYwtaLCIRJdWwN4BFb2yixh
   HCpirWCLoVhvGrwtz0h+1hqbnNGnLHRQ432+Ao7unGZaxG36lg35hzx3Uuw66CK/
   kUjI1qlzuY4JDlTS8AisGkRRPm+vlQIDAQABo1AwTjAdBgNVHQ4EFgQUoZ+z0iKo
   S/BZT/+q+Uh/w+M/oRYwHwYDVR0jBBgwFoAUoZ+z0iKoS/BZT/+q+Uh/w+M/oRYw
   DAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEATWmO43YLumB/KvAF/hYq
   wHsJuU9x3pkOnMmjdw98cqDpTq6zhRqGYwRxT5Vmw0fc0Ws8L0W/nfoHEfvOUeLu
   7Byou0+JnIxHIRzlsIB3ntoFfaQb12nHyoK+UZKx/ri6WPZWE8BpvpLB+bjCue0U
   9Ac/fFXN4vYQX5OqjGtsXAGAMIwMTlhEhd0NZXwZCKgxP6cxCqX2NAvUOMKaVF/9
   erXPGUPoxA/Hn6hWBNGYWNk7CPPlwSeR3IxeANFy3qZ+2U0kWrtX+3qX3/J7OCE3
   TgTKIiwrZqwVMdh2DwbYLJkxsgpCtjY2L6EmWzbQUwxyDf90UlnzpMULNdLf0hto
   LQ==
   -----END CERTIFICATE-----
logfile_paths:
    - /var/log/messages
    - /var/log/auth.log
    - /var/log/syslog
