---
# Debian-related tasks
- include: install.yml
- { include: install-ui.yml, when: consul_is_ui == true }
- include: dnsmasq.yml
- include: consulate.yml
- include: service.yml

# Force a restart of the consul service at the end of every run
- name: Restart Consul
  command: /bin/true
  notify: restart consul
