---
# include the distro-specific stuff
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == "Amazon"


 ## Generic installation parameters
- name: Install the config file
  template:
      src: consul.json.j2
      dest: /etc/consul/consul.json
      owner: consul
      group: consul
      mode: 0644
  notify: restart consul

- name: consul create nginx config
  template:
    src: consul-nginx.conf.j2
    dest: /etc/nginx/sites-enabled/consul
    owner: root
    group: root
    mode: 0644
  when: consul_is_ui
  notify:
    - restart nginx

- name: Configure the firewall rules for the Server
  firewalld:
    port: 8300-8302/tcp
    state: enabled
    permanent: true
    immediate: true

- name: Configure the firewall rules so Swarm can connect
  firewalld:
    port: 8500/tcp
    state: enabled
    permanent: true
    immediate: true

- name: configure dnsmasq
  copy:
    content: 'server=/{{ consul_domain }}/127.0.0.1#8600'
    dest: /etc/dnsmasq.d/10-consul
  notify:
    - restart dnsmasq

- name: Start the service
  service:
      name: consul
      state: running
      enabled: True
