---
# Debian/Ubuntu specficic actions
- name: Ensure the apt caches are uptodate
  apt: update_cache=yes

- name: Ensure common packages are installed
  apt:  name={{ item }} state=present
  with_items: deb_common_packages

- name: Prevent services from starting when package is installed
  copy: src=policy-rc.d dest=/usr/sbin/policy-rc.d owner=root group=root mode=0755

