---
# tasks file for elasticsearch
# include the distro-specific stuff
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
#
- include: rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Start Elasticsearch Service
  service: name=elasticsearch state=running enabled=yes

- name: Copy the elasticsearch config into place
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart_elasticsearch

- name: Register with Consul
  consul:
      service_name: elasticsearch
      service_port: 9200
  when: consul_enabled and consul_enabled == True

- name: Enable the relevant plugins
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install {{ item }} --batch"
  ignore_errors: true
  with_items:
    - x-pack

- name: Enable traffic for all inbound connections
  firewalld:
    port: 9200-9305/tcp
    permanent: true
    state: enabled
    immediate: true
