---
# RHEL/CentOS specific code for ElasticSearch

- name: Add the elasticsearch key to the system
  command: rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch

- name: Add the elasticsearch repo to the system
  copy: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644

- name: Install elasticsearch
  yum: name=elasticsearch state=present

- name: Set the Elasticsearch Defaults
  template: src=etc_default_elasticsearch dest=/etc/sysconfig/elasticsearch owner=root group=root mode=644
  notify: restart_elasticsearch

