---
# tasks file for kibana

- name: Start the kibana service
  service: name=kibana state=started

- name: Insert the Kibana Service definition into Consul
  copy: src=kibana.service.consul dest=/etc/consul.d/kibana.service.json
  when: consul_enabled and consul_enabled == True

- name: Install and enable the kibana plugins
  command: "/opt/kibana/bin/kibana plugin --install {{ item }}"
  ignore_errors: true
  with_items:
    - elasticsearch/marvel/latest

- name: Open the firewall for Kibana
  firewalld:
    port: 5601/tcp
    immediate: true
    permanent: true
    state: enabled
