---
# RHEL/CentOS specific code for Kibana

- name: Add the kibana key to the system
  command: rpm --import https://packages.kibana.org/GPG-KEY-elasticsearch

- name: Add the kibana repo to the system
  copy:
      src: kibana.repo
      dest: /etc/yum.repos.d/kibana.repo
      owner: root
      group: root
      mode: 0644

- name: Install kibana
  yum:
      name: kibana
      state: present
