---
### Debian-specific

- name: Install Firewalld (Debian/Ubuntu)
  apt:
    name: firewalld
    state: present
    update_cache: yes

- name: Start firewalld
  service:
    name: firewalld
    state: running
    enabled: yes

- name: Wait for firewalld to start
  action: command firewall-cmd --state
  register: firewall_cmd_output
  until: firewall_cmd_output.stdout.find('not running') == -1
  retries: 10
  delay: 5

- name: Install python2
  apt:
    name: python2.7
    state: present
    update_cache: yes
