---
### RHEL Specific

- name: Install Firewalld (RHEL/CentOS)
  yum:
    name: firewalld
    state: present
    update_cache: yes

- name: Start firewalld
  service:
    name: firewalld
    state: running
    enabled: yes

- name: Wait for firewalld to start
  action: command firewall-cmd --state
  register: firewall_cmd_output
  until: firewall_cmd_output.stdout.find('not running') == -1
  retries: 10
  delay: 5

# Make sure that we can SSH to the box
- firewalld:
   service: ssh
   permanent: true
   state: enabled
